### PR TITLE
add support to sign commits

### PR DESCRIPTION
**Pull request by onmax**

### CODE REVIEW

**Comment by onmax** [comment]
Please feel free to change whatever it needs. Thanks for making this tool. I recently did a GitHub Action: https://github.com/onmax/oai-createcompletion-githubaction

**Comment by spenserblack** [comment]
Since `-S` = `--gpg-sign` and `-s` = `--signoff`, I wonder if maybe the input should be `G` for **GPG** sign (or something else) so that **S**ignoff is still available :thinking: Or maybe it would be reasonable for uppercase `S` to be sign, and lowercase `s` to be signoff.

******

Or perhaps there could be an input for extra git commit flags so that any number of additional CLI options could be used (`--no-verify`, `--fixup=HEAD`, `--allow-empty`). It might make sense for `aicommits` to just take the args from `process.argv` and pass them to `git commit`, so that, for example, one could use `aicommits -S`. An added bonus is that passing `-m` multiple times appends to the commit message, so one could do something like `aicommits -m "Here is a footer"`.

******

Just throwing some things out there to think about, but signature support alone is awesome! :+1:

**Comment by privatenumber** [comment]
I think ideally we should make the CLI as transparent as possible so it passes down flags it doesn't recognize to `git commit` rather than trying to handle it.

Would it make sense to just do: `aicommits -S`?

**Comment by rek** [comment]
I agree with @privatenumber here, passing through all these standard git flags will give us way more flexibility and allow for easier scripting to be built on top of this in the future.

**Comment by privatenumber** [comment]
Closed in favor of https://github.com/Nutlope/aicommits/pull/70

And reminder since so many people seem to be passing in `-S` every time:

You can always configure your Git to sign commits by default:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Pull request closed without merging**
