### PR TITLE
Refactor and features

### PR DESCRIPTION
**Pull request by privatenumber**
Sorry for the massive PR! I made all the changes in my fork at once since there was a lot to do and I was going to iterate much faster this way.

I adopted most of the changes from the PRs on the repo as well.

### Features
- Added `--help` flag
- Added `dotenv` for detecting env variables from `.env` file
- Renamed `OPENAI_API_KEY` to `OPENAI_KEY` for conciseness
- With pkgroll, the package is bundled and minified so it's faster to install with npx.
- Major UI enhancement. See screenshots below. Used https://www.npmjs.com/package/@clack/prompts
- Updated the API request to return 3 results. The user can pick one to choose from a list and edit it before committing it
- Added an edit step for users to modify the commit message before committing

### DX enhancements
- Use `openai` package instead of manually constructing the request with `node-fetch`. I figured the benefit of having types and error-handling was worth it.
- pkgroll for bundling and development improvement. See [`CONTRIBUTING.md`](https://github.com/privatenumber/aicommits/blob/main/.github/CONTRIBUTING.md).
- Added GitHub Actions for linting and type-checking PRs
- Added ESLint
- Added simple-git-hooks & lint-staged for pre-commit linting

### Refactors
- Organized the repository by `src`, `dist`, and `.github`
- Refactored the GPT-3 prompt to be more concise
- Abstracted out utility functions to `utils.ts` so the code is more semantic

## Try it out
```
npx 'privatenumber/aicommits#npm/main'
```

Help flag:
```
npx 'privatenumber/aicommits#npm/main' --help
```

### CODE REVIEW

**Comment by Nutlope** [comment]
Amazing PR @privatenumber, thanks so much! This changes a ton in the CLI and I'm wondering if it's better to give you contributor access to you can open up branches to break it up a little, since I'd love to merge some of this stuff and some of it is going to require more discussion and back and forth. Thoughts?

**Comment by privatenumber** [comment]
Responded on DM but yeah, would love contributor access. And please let me know which changes you'd like right away vs discuss further.

**Comment by privatenumber** [comment]
Also, I'm re-thinking the edit message step:

Instead of providing our own text editor, Git also has a commit editor so I think we should use that to respect any Git configurations users may have. I think the best way is to write the commit message to a temporary file and spawn `git commit` with the [`--template`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---templateltfilegt) flag.

**Comment by Nutlope** [comment]
@privatenumber Awesome, just gave you contributor access. What I think can be merged right away:

- UI upgrade by migrating to Clack
- Updating the API request to return 3 results (but putting this behind a feature flag since it will be more expensive. I'd still love the default to be one commit)
- Use openai package
- Repo organization
- GPT-3 prompt refactor
- Abstracting out utility functions to utils.ts

Feel free to open individual PRs for these or one big PR with all of them! Going to leave another message here with questions about the other things you suggested adding, which we can discuss either here or in the individual PRs.

**Comment by Nutlope** [comment]
Questions about your other changes:

1. Added dotenv for detecting env variables from .env file – is this for folks who would have a `.env` file in the root of their computer? Where is this env file exactly and why is this helpful?
2. What exactly is in the `--help` flag and why is that helpful? I merged a PR earlier today that logs any errors from OpenAI's API so I'm wondering if this is still useful
3. Unsure about mandating a `OPENAI_KEY=<token> npx aicommits` syntax. Would this be better than what currently exists with the global install, setting the OpenAI key, then just using `aicommits`?
4. For `pkgroll`, would love to see the PR for this one specifically and we can talk about. I think it would be a great improvement, I just want to try to better understand what it would be used for and how it works
5. Same goes for the GitHub actions, simple-git-hooks, & lint-staged, would love to see these in a separate PR

**Comment by Nutlope** [comment]
Overall, truly fantastic work @privatenumber. Thank you so much for all these wonderful changes!

**Comment by privatenumber** [comment]
I merged in most of the approved changes. Will address the rest over the next few days.


To your points:

1. I opened a PR for dotenv support here: https://github.com/Nutlope/aicommits/pull/42 Hopefully the PR description answers your questions.


2. `--help` flag is just the convention for CLI commands to store the manual or README for the command. (e.g. `git --help` shows how to use the `git` command.) So when you pass in `--help`, it logs a brief description about it and how to use it, then exists.

3. The best approach would definitely be the dotenv approach, since it's the most secure. `OPENAI_KEY=<token> npx aicommits` is slightly more secure because it only sets `OPENAI_KEY` for that particular command, so other commands later can't access the secret token. I added that in the "quick usage" guide because it's the fastest way to get started. But once users install the command and use it regularly, they should move the token to `~/.aicommits`.

4. For sure! Excited for this one because it's a huge DX win.

5. Sounds good 👍

**Comment by Nutlope** [comment]
@privatenumber Is everything from here merged already? Should we keep this PR open still?

**Comment by privatenumber** [comment]
Yup! Closing...

**Pull request closed without merging**
