### PR TITLE
added GPT3Tokenizer to count prompt tokens

### PR DESCRIPTION
**Pull request by lhr0909**
Added GPT3Tokenizer to count prompt tokens. Token count is currently set to 4000 so it has some buffer before maxing out the 4096 token limit. I noticed we are using the `text` model so I am keeping the initialization to `gpt3` type. But `codex` token counting is accepted too, in case we want to switch to the `code` model.

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for this PR.

The [official recommendation](https://platform.openai.com/tokenizer) seems to suggest using [`gpt-3-encoder`](https://www.npmjs.com/package/gpt-3-encoder).

What do you think of using that? What are the differences?

**Comment by lhr0909** [comment]
So gpt-3-encoder doesn't have token logic to work with codex models. This lib rips source code directly from the Tokenizer page from OpenAI so it has codex logic included. Since we are doing code related work and if someone has codex model, he could try to use that instead of the text-only model. Also this lib uses a faster map implementation for the token lookup, so it should be a bit quicker.

I am a bit biased because I made this lib myself. But if you check the repo on GitHub, Microsoft, Raycasr and promptable are using my tokenizer. Happy to support it if we need more features later.

Cheers!

**Comment by transitive-bullshit** [comment]
I created a benchmark to test the correctness and performance of all the various Node.js BPE tokenizers.

The recently introduced Rust WASM port of OpenAI's official `tiktoken` wins out in all regards (port by @dqbd).

https://github.com/transitive-bullshit/compare-tokenizers

<p align="center">

</p>

@lhr0909 would love to get your feedback on the benchmark. I'm not tied to any one solution; I just want the to Node.js community to improve by making choices based on data. 😄

**Comment by privatenumber** [comment]
Thanks for sharing @transitive-bullshit 

Few questions:
- I'm wondering if performance is that important here or if it will be negligible on most diff inputs using aicommits. How big of an input do you need to get speeds of over 1,000ms?

- Currently, I'm more interested in correctness. Why are there discrepancies in these two results? And what's correct?
```
8) 3189 chars "Enter [two Players a..." ⇒ {
  'gpt3-tokenizer': 876,
  'gpt-3-encoder': 876,
  '@dqbd/tiktoken gpt2': 876,
  '@dqbd/tiktoken text-davinci-003': 872
}
9) 17170 chars "ANTONY. [To CAESAR] ..." ⇒ {
  'gpt3-tokenizer': 5801,
  'gpt-3-encoder': 5801,
  '@dqbd/tiktoken gpt2': 5801,
  '@dqbd/tiktoken text-davinci-003': 5306
}
```

**Comment by transitive-bullshit** [comment]
> I'm wondering if performance is that important here or if it will be negligible on most diff inputs using aicommits. How big of an input do you need to get speeds of over 1,000ms?

Agreed; speed probably isn't as important of a factor here.

> Currently, I'm more interested in correctness. Why are there discrepancies in these two results? And what's correct?

`gpt3-tokenizer` and `gpt-3-encoder` both use the `gpt2` encoding .

The Rust version is a wasm port of OpenAI's official [tiktoken](https://github.com/openai/tiktoken) Rust lib.

The `'@dqbd/tiktoken text-davinci-003'` results are accurate for `text-davinci-003` whereas the others are all based on an older encoding that was used for `gpt2`.

My recommendation both for speed and correctness would be to go with the wasm port. (I've tested it on node.js 12+)

**Comment by lhr0909** [comment]
Same! I took the time to reverse-engineer the tokenizer when there wasn't one for Codex models. Now that there is an official tokenizer available, I am all for using that 😄 Thanks @transitive-bullshit for taking the time to benchmarking the solutions!

**Comment by privatenumber** [comment]
Thanks yall

@lhr0909 Would you mind updating the PR to use @dqbd/tiktoken?

**Comment by lhr0909** [comment]
@Nutlope Will do that in a few hours!

**Comment by lhr0909** [comment]
reopened #114

**Pull request closed without merging**
