### PR TITLE
Support Signed commits

### PR DESCRIPTION
**Pull request by Mahmoudgalalz**
Hello, I'm sending this pr according to this #85 issue

I'm open for reviews 
@privatenumber 
@Nutlope

### CODE REVIEW

**Comment by privatenumber** [comment]
Support for signed commits will be handled via https://github.com/Nutlope/aicommits/pull/70, where you can simply pass in flags to provide to the underlying git

**Comment by Mahmoudgalalz** [comment]
I think I'm giving this option to the person if he already have the GPG Key for github I think it shouldn't be a flag it will be so messy for many flags
I think if anyone using GPG key he will used all the time so it should be applied automatically with just a confirm option 
@privatenumber @Nutlope 
I think we should consider this way

**Comment by privatenumber** [comment]
For automatically signing all commits by default, you can configure your git: [`git config --global commit.gpgsign true`](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

Any feature built-into git, we don't want to re-invent. Otherwise it will create a maintenance burden on us.

**Comment by Mahmoudgalalz** [comment]
it was the first time that I know that, thanks btw

**Comment by privatenumber** [comment]
Closing in favor of #70

**Pull request closed without merging**
