### PR TITLE
ci: add github actions for linting & type-checking

### PR DESCRIPTION
**Pull request by privatenumber**
## Problem
When contributors open PRs, there are no basic checks that help with streamlining review.

## Changes
Add GitHub Actions to automatically check if the code builds and passes the linter.

### CODE REVIEW

**Comment by privatenumber** [comment]
@Nutlope Cool to merge this in?

**Review by Nutlope — APPROVED** [review]
Yes, LGTM!

**Comment by privatenumber** [comment]
@Nutlope Can you update the repo settings to recommend PRs be up to date with the base branch?

Screenshot 2023-02-16 at 10 58 14 AM

**Comment by Nutlope** [comment]
@privatenumber done!

**Pull request merged**
