### PR TITLE
feat: enable Conventional Commits standard as flag

### PR DESCRIPTION
**Pull request by ThijSlim**
Split of the big PR into a PR that only contains changes to support Conventional Commits standard https://www.conventionalcommits.org/en/v1.0.0/

- This change contains the option to configure conventional commits as flag
- Improved on the testing strategy, because it was really hard to test my changes. Added `vitest` as testing framework to run tests concurrently and include test cases with git diffs generated by ChatGPT

### CODE REVIEW

**Comment by privatenumber** [comment]
I'm hoping to find some time to work on this project over the weekend, fingers crossed. My plan is to get the smaller PRs in first.

By the way, I noticed that this PR has 20 files changed. I thought you said the [new PR has 4 files](https://github.com/Nutlope/aicommits/pull/163#issuecomment-1481399428)? Wondering if this PR is up to date.

Upon skimming through it, it appears that it could be divided into smaller changes. For example, documentation changes or editorconfig changes seem straightforward and probably don't need to be held up by the rest of this PR. It would also be beneficial to have the test refactors in a separate PR, as they're low priority and will likely require further discussion.

**Comment by thijslimmen** [comment]
I could remove the changes to README and editor config. I understand that it could be part of a follow up PR.

the whole test refactor was required for me to iterate really fast on the changes I was making to the prompt. I would not say that it is low priority. Also for follow up PRs having these tests is really beneficial.

I would suggest to checkout this PR and run m the tests, I am sure that you will like it.

Let me know if you don’t agree on what I wrote above. :)

**Comment by thijslimmen** [comment]
And the PR is up to date as of now

**Comment by thijslimmen** [comment]
I will make it even smaller 👍🏻

**Comment by thijslimmen** [comment]
@privatenumber Extracted the changes to the tests to the following PR:
https://github.com/Nutlope/aicommits/pull/170/files

**Comment by thijslimmen** [comment]
I created a new PR that only includes minimal changes needed for Conventional commits #177 (including neccesary tests)

**Comment by thijslimmen** [comment]
I created a new PR that only includes minimal changes needed for Conventional commits #177 (including neccesary tests)

**Pull request closed without merging**
